-- Anagrafica gestionale: estende customers con tutti i campi dell'export Mexal/Passepartout.
-- Tutti i campi sono nullable, niente vincoli FK (i codici sono tecnici del gestionale di origine).

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS cli_cod                                  text,
  ADD COLUMN IF NOT EXISTS cli_codice                               text,
  ADD COLUMN IF NOT EXISTS cli_ultima_modifica                      timestamptz,
  ADD COLUMN IF NOT EXISTS cli_nome                                 text,
  ADD COLUMN IF NOT EXISTS cli_nome_f                               text,
  ADD COLUMN IF NOT EXISTS cli_nome_l                               text,
  ADD COLUMN IF NOT EXISTS cli_indi                                 text,
  ADD COLUMN IF NOT EXISTS cli_cap                                  text,
  ADD COLUMN IF NOT EXISTS cli_citta                                text,
  ADD COLUMN IF NOT EXISTS cli_prov                                 text,
  ADD COLUMN IF NOT EXISTS cli_nazione                              text,
  ADD COLUMN IF NOT EXISTS cli_tel                                  text,
  ADD COLUMN IF NOT EXISTS cli_tel2                                 text,
  ADD COLUMN IF NOT EXISTS cli_fax                                  text,
  ADD COLUMN IF NOT EXISTS cli_tel_cell                             text,
  ADD COLUMN IF NOT EXISTS cli_email                                text,
  ADD COLUMN IF NOT EXISTS cli_rec_iva                              text,
  ADD COLUMN IF NOT EXISTS cli_cod_fisc                             text,
  ADD COLUMN IF NOT EXISTS cli_part_iva                             text,
  ADD COLUMN IF NOT EXISTS cli_pers_fisi                            boolean,
  ADD COLUMN IF NOT EXISTS cli_sesso                                text,
  ADD COLUMN IF NOT EXISTS cli_nat_data                             date,
  ADD COLUMN IF NOT EXISTS cli_nat_com                              text,
  ADD COLUMN IF NOT EXISTS cli_nat_prov                             text,
  ADD COLUMN IF NOT EXISTS cli_ass_o_cp                             text,
  ADD COLUMN IF NOT EXISTS cli_ban_iban                             text,
  ADD COLUMN IF NOT EXISTS cli_ban_cc                               text,
  ADD COLUMN IF NOT EXISTS ban_cod                                  text,
  ADD COLUMN IF NOT EXISTS prof_cod                                 text,
  ADD COLUMN IF NOT EXISTS pag_cod                                  text,
  ADD COLUMN IF NOT EXISTS cli_ban_cin                              text,
  ADD COLUMN IF NOT EXISTS cli_note                                 text,
  ADD COLUMN IF NOT EXISTS cli_codice_conto                         text,
  ADD COLUMN IF NOT EXISTS cli_pat_num                              text,
  ADD COLUMN IF NOT EXISTS cli_pat_cat                              text,
  ADD COLUMN IF NOT EXISTS cli_pat_by                               text,
  ADD COLUMN IF NOT EXISTS cli_pat_data_ril                         date,
  ADD COLUMN IF NOT EXISTS cli_pat_data_scad                        date,
  ADD COLUMN IF NOT EXISTS cli_consenso_trattamento_dati            boolean,
  ADD COLUMN IF NOT EXISTS cli_cartaid                              text,
  ADD COLUMN IF NOT EXISTS cli_cartaid_ril_da                       text,
  ADD COLUMN IF NOT EXISTS cli_cartaid_ril_data                     date,
  ADD COLUMN IF NOT EXISTS cli_cartaid_data_scad                    date,
  ADD COLUMN IF NOT EXISTS prs_cod_contatto                         text,
  ADD COLUMN IF NOT EXISTS prs_cod_segnalato_da                     text,
  ADD COLUMN IF NOT EXISTS cli_iva_esigibilita_differita            boolean,
  ADD COLUMN IF NOT EXISTS cli_codice_indice_pubblica_amministrazione text,
  ADD COLUMN IF NOT EXISTS cli_id_iso_nazione                       text,
  ADD COLUMN IF NOT EXISTS cli_titolo                               text,
  ADD COLUMN IF NOT EXISTS cli_codice_eori                          text,
  ADD COLUMN IF NOT EXISTS cli_id_iso_nazione_sede                  text,
  ADD COLUMN IF NOT EXISTS cli_id                                   text,
  ADD COLUMN IF NOT EXISTS cli_split_payment                        boolean,
  ADD COLUMN IF NOT EXISTS cativa_id                                text,
  ADD COLUMN IF NOT EXISTS cli_indi_lat                             numeric,
  ADD COLUMN IF NOT EXISTS cli_pat_estera                           boolean,
  ADD COLUMN IF NOT EXISTS cli_pat_ril_luogo                        text,
  ADD COLUMN IF NOT EXISTS cli_indi_lng                             numeric,
  ADD COLUMN IF NOT EXISTS cli_destinatario_codice                  text,
  ADD COLUMN IF NOT EXISTS cli_pec                                  text,
  ADD COLUMN IF NOT EXISTS cli_indirizzo_numero                     text,
  ADD COLUMN IF NOT EXISTS rf_id                                    text,
  ADD COLUMN IF NOT EXISTS cli_riferimento_amministrazione          text,
  ADD COLUMN IF NOT EXISTS cli_cnt_id                               text,
  ADD COLUMN IF NOT EXISTS cli_data_creazione                       timestamptz;

CREATE INDEX IF NOT EXISTS customers_cod_fisc_idx  ON public.customers (cli_cod_fisc);
CREATE INDEX IF NOT EXISTS customers_part_iva_idx  ON public.customers (cli_part_iva);
CREATE INDEX IF NOT EXISTS customers_cli_cod_idx   ON public.customers (cli_cod);
